baseURL = "/"
languageCode = "en-us"
title = "Koenighotze Energy Emporium"
copyright = "David Schmitz"

[author]
  name = "David Schmitz"
  profile = ""

# markup:
#   highlight:
#     codeFences: true
#     guessSyntax: false
#     hl_Lines: ""
#     lineNoStart: 1
#     lineNos: false
#     lineNumbersInTable: true
#     noClasses: true
#     tabWidth: 2

# privacy:
#   disqus:
#     disable: true
#   googleAnalytics:
#     anonymizeIP: true
#     respectDoNotTrack: true
#     useSessionStorage: false

[taxonomies]
   tag = "tags"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Koenighotze Energy Emporium"
    description = "Random stuff about coding, architecture and whatever I find interesting."
    github = "https://github.com/koenighotze"
    twitter = "https://twitter.com/koenighotze"
    linkedin = "https://www.linkedin.com/in/david-schmitz-636ab725/"
    email = "koenighotze@gmail.com"
    shareTwitter = true
    shareLinkedIn = true
    dateFormat = "Jan 2, 2006"
    readingTime = true
    readingTimeText = "Estimated reading time:"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 1

[[menu.main]]
    name = "Talks and Presentations"
    url = "/page/talks-and-presentations/"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "vs"
    # style = "monokailight"
    tabWidth = 4
