# Welcome to Jekyll!
#
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Koenighotze Energy Emporium
email: koenighotze_NO_SPAM@gmail.com
description: >
  This site is just a collection of random stuff about coding, architecture and whatever
  I find interesting. Topics include serverless, devops, microservices, agile software delivery.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://koenighotze.de"
twitter:
  username: koenighotze
logo: /assets/images/IMG_0011-2.jpg
social:
  name: David Schmitz
  links:
    - https://twitter.com/koenighotze
    - https://www.linkedin.com/in/david-schmitz-636ab725/
    - https://github.com/koenighotze
    - https://keybase.io/koenighotze
lang: en
twitter_username: koenighotze
github_username:  koenighotze
github.repository_url: https://github.com/koenighotze/koenighotze.github.io.git
markdown: kramdown
theme: jekyll-theme-architect
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - support/
  - ideas/
  - build.sh
  - README.md
bootstrap:
  assets: true
author:
  twitter: koenighotze

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
