name: Validate

on: 
  pull_request:
  workflow_dispatch:

jobs:
  
  lint-posts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: xt0rted/markdownlint-problem-matcher@v1
      - run: markdownlint content/post/
