name: Validate

on: 
  push:
    branches:    
      - master
  pull_request:
  workflow_dispatch:

jobs:
  
  lint-posts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run lint-posts
